title: Cards, Claps, and Code
hero_image: images/banner.png
description: unplugged activity using cards and claps to create a programming language.
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: Cards, Claps, and Code
